### PR TITLE
add subcommand supports.

### PR DESCRIPTION
**Pull request by cupen**
See #3

### CODE REVIEW

**Comment by cupen** [comment]
```python
import cbox

@cbox.cmd
def hello(name: str):
    """greets a person by its name.

    :param name: the name of the person
    """
    print('hello name={name}!'.format(**locals()))

@cbox.cmd
def world(name: str):
    """greets a person by its name.

    :param name: the name of the person
    """
    print('world name={name}!'.format(**locals()))


if __name__ == '__main__':
    cbox.main([hello, world])

```

# help text.
```bash
$ python yourscript.py --help
usage: subcommands.py [-h] {hello,world} ...

which subcommand do you want?

optional arguments:
  -h, --help     show this help message and exit

subcommands:
  {hello,world}
    hello        greets a person by its name.
    world        greets a person by its name.
```

# wrong sub-command.
```
$ python yourscript.py  subcmd_wrong --blah --blah
usage: subcommands.py [-h] {hello,world} ...
subcommands.py: error: argument subcmd: invalid choice: 'subcmd_wrong' (choose from 'hello', 'world')
```

# help text of sub-command.
```
$ python yourscipt.py  hello --help
usage: subcommands.py world [-h] --name NAME

optional arguments:
  -h, --help   show this help message and exit
  --name NAME  the name of the person
```
# run it.
```
$ python yourscipt.py  hello --name foo
hello name=foo!
```

**Comment by cupen** [comment]
@shmuelamar  Hello!

**Comment by shmuelamar** [comment]
hey @cupen again! great feature i think of using it on my other projects :)

great PR and I just edited some pep8 issues (apparently i didnt add flake8 to CI only to `make test` command, ill add them soon).

please review the changes i pushed and merge / update them.

**Review by cupen — COMMENTED** [review]
Good job.

**Comment by cupen** [comment]
@shmuelamar  I get it to my local repo, it works fine.  That's really good.

**Pull request merged**
